window.CHEESES = (window.CHEESES || []).concat([
  {
    "id": "butterkase",
    "schemaVersion": 2,
    "mildStinky": 1,
    "softHard": 3,
    "isBizarreLore": false,
    "name": "Butterkäse",
    "country": "Germany",
    "region": "Europe",
    "family": "semi-soft",
    "milk": "Cow",
    "origin": "Germany (also produced in Austria)",
    "history": "Developed in the early 20th century in Germany as a deliberately mild, buttery cheese aimed at popular taste — its name literally means 'butter cheese,' describing both its rich flavor and its smooth, buttery texture.",
    "prevalence": "A popular everyday cheese in Germany and among German-American communities in the US Midwest, especially Wisconsin.",
    "usage": "Melted onto sandwiches and burgers, sliced for snacking, or served alongside cold cuts.",
    "texture": "Semi-soft, smooth, and pale yellow, mild and creamy with a slight tang.",
    "fact": "Butterkäse was essentially designed to be inoffensive — created as a crowd-pleasing, mild alternative to stronger German cheeses, it remains one of the few classic European cheeses whose entire reputation rests on being reliably gentle rather than bold."
  },
  {
    "id": "jarlsberg",
    "schemaVersion": 2,
    "mildStinky": 2,
    "softHard": 5,
    "isBizarreLore": true,
    "name": "Jarlsberg",
    "country": "Norway",
    "region": "Europe",
    "family": "semi-hard",
    "milk": "Cow",
    "origin": "Jarlsberg, Norway",
    "history": "Developed in the mid-20th century by Norwegian food scientists modeling their cheese on Swiss Emmental, using a specially selected bacterial culture to produce large, characteristic holes. It was patented and trademarked, making it one of the few classic-style cheeses actively protected by intellectual property law rather than geographic rules.",
    "prevalence": "Norway's best-known cheese export, sold in over 90 countries and one of the most widely available 'Swiss-style' cheeses outside Switzerland.",
    "usage": "Sliced for sandwiches and cheese boards, melted into gratins, or served with crackers and fruit.",
    "texture": "Semi-firm, smooth, and pale yellow with large holes, mild and slightly sweet-nutty in flavor.",
    "fact": "Jarlsberg is technically a trademarked brand rather than a protected regional name — the recipe and even the specific bacterial culture that creates its holes were patented by Norwegian researchers, meaning 'genuine' Jarlsberg is defined by corporate ownership rather than geography."
  },
  {
    "id": "brunost",
    "schemaVersion": 2,
    "mildStinky": 1,
    "softHard": 6,
    "isBizarreLore": true,
    "name": "Brunost (Gjetost)",
    "country": "Norway",
    "region": "Europe",
    "family": "whey-other",
    "milk": "Goat and/or Cow (whey)",
    "origin": "Norway",
    "history": "Not a cheese in the traditional sense but a caramelized whey product, invented in 1863 by Anne Hov, a farmer's wife who found a way to boil down leftover whey, cream, and milk sugars into a solid, sweet brown block — turning what was previously discarded farm waste into a beloved national food.",
    "prevalence": "One of Norway's most iconic foods and a fixture of Norwegian breakfast tables, though little known outside Scandinavia.",
    "usage": "Sliced thin with a special cheese slicer (the ostehøvel, itself a Norwegian invention) and eaten on bread or waffles.",
    "texture": "Dense, smooth, and fudge-like, with a sweet, caramel flavor from its concentrated milk sugars.",
    "fact": "In 2013, a truck carrying 27 tons of Brunost caught fire inside a road tunnel in northern Norway; the cheese's high fat and sugar content made it burn almost like gasoline, and the resulting blaze took firefighters four days to extinguish and shut the tunnel down for weeks of repairs."
  },
  {
    "id": "havarti",
    "schemaVersion": 2,
    "mildStinky": 2,
    "softHard": 3,
    "isBizarreLore": false,
    "name": "Havarti",
    "country": "Denmark",
    "region": "Europe",
    "family": "semi-soft",
    "milk": "Cow",
    "origin": "Denmark",
    "history": "Named after Havarthigaard, the farm outside Copenhagen where 19th-century cheesemaker Hanne Nielsen developed the recipe after touring cheese dairies across Europe to study different techniques, blending ideas from several traditions into one distinctly Danish cheese.",
    "prevalence": "Denmark's best-known cheese internationally, widely produced and sold across Europe and North America.",
    "usage": "Sliced for sandwiches, melted into grilled cheese, or served with crackers and fruit; flavored versions (dill, caraway, jalapeño) are common.",
    "texture": "Semi-soft, smooth, and buttery with small irregular holes.",
    "fact": "Hanne Nielsen, who developed Havarti, was an unusually well-traveled 19th-century woman for her time — she toured cheese-producing regions across Europe specifically to bring new techniques home, essentially acting as her own one-woman research-and-development team for Danish dairy.",
    "images": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Cream_havarti_on_bread.jpg",
        "alt": "Havarti cheese on bread",
        "credit": "Wikimedia Commons"
      }
    ]
  },
  {
    "id": "skyr",
    "schemaVersion": 2,
    "mildStinky": 2,
    "softHard": 2,
    "isBizarreLore": false,
    "name": "Skyr",
    "country": "Iceland",
    "region": "Europe",
    "family": "whey-other",
    "milk": "Skimmed Cow's Milk",
    "origin": "Iceland",
    "history": "Brought to Iceland by Norse settlers over a thousand years ago and preserved largely unchanged since. Despite its cheese-like texture, Skyr is technically a soft cultured dairy product closer to strained yogurt, made using a skyr-specific bacterial culture passed down for generations.",
    "prevalence": "A cornerstone of Icelandic cuisine for centuries, and — in recent decades — a global health-food export, marketed worldwide as a high-protein yogurt alternative.",
    "usage": "Eaten plain or with fruit and honey for breakfast, used in baking, or blended into smoothies.",
    "texture": "Extremely thick, smooth, and dense, tangier than regular yogurt but milder than most cheeses.",
    "fact": "Because true Skyr requires a specific live culture, most 'skyr' cultures used worldwide today can trace their lineage directly back to Icelandic farms — some producers describe their starter culture as an unbroken chain passed down since the Viking Age."
  },
  {
    "id": "bryndza",
    "schemaVersion": 2,
    "mildStinky": 5,
    "softHard": 2,
    "isBizarreLore": false,
    "name": "Bryndza",
    "country": "Slovakia",
    "region": "Europe",
    "family": "fresh",
    "milk": "Sheep",
    "origin": "Slovakia (also made in Poland, Hungary, Romania, and Ukraine)",
    "history": "A soft, salty sheep's-milk cheese made across the Carpathian mountain range for centuries by shepherd communities, traditionally produced during the summer grazing season in mountain huts called 'salaše.'",
    "prevalence": "A national dish ingredient in Slovakia, where it's the star of bryndzové halušky, considered the country's unofficial national dish.",
    "usage": "The essential ingredient in bryndzové halušky (potato dumplings with bryndza and bacon), spread on bread, or mixed into savory pastries.",
    "texture": "Soft, crumbly, and spreadable, with a distinctly salty, tangy sheep's-milk flavor.",
    "fact": "Slovak Bryndza received EU Protected Geographical Indication status, formally distinguishing it from similar-sounding cheeses made elsewhere in Central Europe — a rare case of a humble shepherd's cheese getting the same kind of legal protection as luxury European exports like Champagne or Parmigiano Reggiano."
  },
  {
    "id": "oscypek",
    "schemaVersion": 2,
    "mildStinky": 4,
    "softHard": 6,
    "isBizarreLore": true,
    "name": "Oscypek",
    "country": "Poland",
    "region": "Europe",
    "family": "semi-hard",
    "milk": "Sheep (with some Cow)",
    "origin": "Podhale region, Tatra Mountains, Poland",
    "history": "Made by highland shepherds for centuries using milk from sheep grazing in the Tatra Mountains, hand-shaped in traditional carved wooden molds that press decorative patterns into the rind, then brined and cold-smoked over wood fires.",
    "prevalence": "A protected regional specialty (EU PDO) and a strong symbol of Polish highland (Góral) culture, sold at mountain markets and tourist stalls across southern Poland.",
    "usage": "Grilled and served with cranberry sauce as a popular street food, or sliced for a smoky, salty snack.",
    "texture": "Firm, dense, and rubbery with a smoky aroma and salty flavor.",
    "fact": "Only cheese made by hand using milk from a specific breed of sheep grazing the Tatra highlands, shaped in traditional carved wooden molds, and smoked the traditional way can legally be called Oscypek under EU rules — making its decorative pressed pattern a legally protected mark of authenticity, not just decoration."
  },
  {
    "id": "sirene",
    "schemaVersion": 2,
    "mildStinky": 4,
    "softHard": 3,
    "isBizarreLore": false,
    "name": "Sirene",
    "country": "Bulgaria",
    "region": "Europe",
    "family": "fresh",
    "milk": "Cow, Sheep, or Goat",
    "origin": "Bulgaria, nationwide",
    "history": "A white brined cheese similar in style to feta, made in Bulgaria for centuries and considered a defining ingredient of Bulgarian national cuisine, with a long history of independent Balkan brined-cheese traditions.",
    "prevalence": "Bulgaria's most consumed cheese and central to the national diet, eaten daily by many households.",
    "usage": "The essential ingredient in shopska salad (Bulgaria's national salad), baked in banitsa pastry, or eaten simply with bread and tomatoes.",
    "texture": "Firm, crumbly, and salty, similar to feta but often slightly softer and tangier.",
    "fact": "Bulgarians eat more cheese per capita than almost any other nation in Europe, and Sirene — not the more internationally famous Greek feta — is the cheese most credited for that number, appearing at nearly every Bulgarian meal from breakfast to dinner."
  },
  {
    "id": "akkawi",
    "schemaVersion": 2,
    "mildStinky": 2,
    "softHard": 3,
    "isBizarreLore": false,
    "name": "Akkawi",
    "country": "Lebanon / Palestine",
    "region": "Middle East & Africa",
    "family": "fresh",
    "milk": "Cow",
    "origin": "Acre (Akka), historic Palestine and Lebanon coast",
    "history": "Named after the coastal city of Acre (Akka), this mild brined cheese has been made across the Levant for generations and became especially prominent in Palestinian, Lebanese, and Syrian communities and their diasporas.",
    "prevalence": "A staple cheese across the Levant and increasingly available in Middle Eastern grocery stores worldwide.",
    "usage": "The traditional cheese for knafeh, a popular Middle Eastern dessert, also eaten fresh with bread or used in savory pastries.",
    "texture": "Semi-firm, mild, and slightly stretchy when heated, with low salt compared to some other brined cheeses.",
    "fact": "Akkawi's mild flavor and stretchy melt make it the standard choice for knafeh, a dessert where the cheese is topped with sugar syrup and crushed pistachios rather than the usual savory pairings — one of the few cheeses in the world primarily famous as a dessert ingredient."
  },
  {
    "id": "labneh",
    "schemaVersion": 2,
    "mildStinky": 2,
    "softHard": 1,
    "isBizarreLore": false,
    "name": "Labneh",
    "country": "Lebanon / Syria / Palestine / Jordan",
    "region": "Middle East & Africa",
    "family": "fresh",
    "milk": "Cow, Sheep, or Goat (strained yogurt)",
    "origin": "Levant (Lebanon, Syria, Palestine, Jordan)",
    "history": "Made by straining yogurt through cloth for hours or days until it thickens into a soft, spreadable cheese-like paste, a technique used across the Levant for centuries as a way to preserve dairy without refrigeration.",
    "prevalence": "A breakfast and mezze staple across the Middle East, increasingly popular internationally as a yogurt-cheese hybrid.",
    "usage": "Spread on flatbread and drizzled with olive oil as part of a mezze spread, rolled into balls and preserved in olive oil, or used as a dip.",
    "texture": "Thick, smooth, and creamy, tangier than cream cheese but milder than most aged cheeses.",
    "fact": "Because it's made from strained yogurt rather than milk set with rennet, Labneh sits in a gray area between 'cheese' and 'yogurt' that food classification systems still argue about — in much of the Middle East it's simply treated as its own category, no debate necessary."
  },
  {
    "id": "domiati",
    "schemaVersion": 2,
    "mildStinky": 3,
    "softHard": 3,
    "isBizarreLore": true,
    "name": "Domiati",
    "country": "Egypt",
    "region": "Middle East & Africa",
    "family": "fresh",
    "milk": "Buffalo, Cow, or Goat",
    "origin": "Egypt, nationwide",
    "history": "One of the oldest cheese styles still made today, with a lineage some food historians trace back to ancient Egypt. Uniquely, salt is added directly to the milk before curdling rather than afterward, a technique almost unique to Domiati among the world's cheeses.",
    "prevalence": "Egypt's most popular cheese, eaten daily across the country and central to Egyptian breakfast culture.",
    "usage": "Eaten fresh with bread, olives, and vegetables as part of a traditional Egyptian breakfast, or aged and used in cooking.",
    "texture": "Soft and crumbly when fresh, firmer and sharper with age.",
    "fact": "Fragments of cheese believed to date back roughly 3,200 years were discovered in an ancient Egyptian tomb near Saqqara — potentially making a Domiati-like cheese one of the oldest solid foods ever recovered by archaeologists, according to the 2018 study that analyzed the residue."
  },
  {
    "id": "monterey-jack",
    "schemaVersion": 2,
    "mildStinky": 1,
    "softHard": 3,
    "isBizarreLore": false,
    "name": "Monterey Jack",
    "country": "United States",
    "region": "Americas",
    "family": "semi-soft",
    "milk": "Cow",
    "origin": "Monterey, California, USA",
    "history": "Developed from a cheesemaking tradition brought by Franciscan missionaries to California, it was commercialized and popularized in the 1800s by businessman David Jacks, who gave the cheese the name it carries today.",
    "prevalence": "One of a relatively small number of cheese styles considered genuinely American in origin, widely produced and eaten across the US.",
    "usage": "Melted into Mexican-American dishes like quesadillas and nachos, sliced for sandwiches, or blended with Cheddar for 'Colby-Jack.'",
    "texture": "Semi-soft, smooth, and pale, mild and slightly tangy, melts easily.",
    "fact": "David Jacks didn't invent the cheese so much as aggressively market it under his own name after buying up much of the local cheesemaking business — making Monterey Jack one of the few major cheese styles named directly after the entrepreneur who commercialized it rather than its place of origin or inventor."
  }
]);
